export default {
  quiz: {
    questions: [
      {
        id: 1,
        question: "In a meeting, how do you politely disagree with someone?",
        options: [
          "You are wrong.",
          "I see your point, but I think differently.",
          "That is a bad idea.",
          "No."
        ],
        correct: 1,
        explanation: "‘I see your point, but I think differently’ is a polite way to disagree in a business meeting."
      },
      {
        id: 2,
        question: "Which phrase is used to make a suggestion in a meeting?",
        options: [
          "I am busy.",
          "How about we try a different approach?",
          "Let me finish.",
          "That is all."
        ],
        correct: 1,
        explanation: "‘How about + subject + verb’ is a common structure for making suggestions."
      },
      {
        id: 3,
        question: "Which sentence uses the first conditional correctly?",
        options: [
          "If we will lower the price, sales increase.",
          "If we lower the price, sales will increase.",
          "If we lowered the price, sales would increase.",
          "If we lower the price, sales increased."
        ],
        correct: 1,
        explanation: "The first conditional uses 'if + present simple, will + base verb' for real future possibilities."
      },
      {
        id: 4,
        question: "What does 'remain stable' mean in a business context?",
        options: [
          "To increase quickly",
          "To decrease slowly",
          "To stay the same",
          "To fluctuate wildly"
        ],
        correct: 2,
        explanation: "‘Remain stable’ means to stay at the same level without significant change."
      },
      {
        id: 5,
        question: "Which modal verb is most polite for making a request?",
        options: [
          "Can you send the report?",
          "Could you send the report?",
          "Must you send the report?",
          "Should you send the report?"
        ],
        correct: 1,
        explanation: "‘Could’ is more polite and formal than ‘can’ when making a request."
      },
      {
        id: 6,
        question: "Which sentence is in the passive voice?",
        options: [
          "The team prepared the presentation.",
          "The presentation was prepared by the team.",
          "The team is preparing the presentation.",
          "The team will prepare the presentation."
        ],
        correct: 1,
        explanation: "The passive voice uses ‘be + past participle’ — here, 'was prepared'."
      },
      {
        id: 7,
        question: "Choose the correct present perfect sentence:",
        options: [
          "I worked here since 2020.",
          "I have worked here since 2020.",
          "I am working here since 2020.",
          "I will work here since 2020."
        ],
        correct: 1,
        explanation: "Present perfect with 'since' indicates an action that started in the past and continues."
      },
      {
        id: 8,
        question: "Which word order is correct for a presentation sequence?",
        options: [
          "Finally, next, first",
          "First, finally, next",
          "First, next, finally",
          "Next, finally, first"
        ],
        correct: 2,
        explanation: "In presentations, we use 'First, Next, Finally' to structure the flow logically."
      }
    ]
  },

  flashcards: [
    {
      front: "Revenue",
      back: "The total income generated by a business",
      example: "Our revenue increased by 15% this quarter."
    },
    {
      front: "Deadline",
      back: "The latest time by which something must be completed",
      example: "The deadline for the proposal is Friday at 5 PM."
    },
    {
      front: "Quarterly",
      back: "Occurring every three months",
      example: "We have quarterly performance reviews every March, June, September, and December."
    },
    {
      front: "Stakeholder",
      back: "A person with an interest or concern in a business",
      example: "We need to present the report to all stakeholders next week."
    },
    {
      front: "Agenda",
      back: "A list of items to be discussed in a meeting",
      example: "Did everyone receive the agenda for today's meeting?"
    },
    {
      front: "Outsource",
      back: "To obtain work from an external company",
      example: "We decided to outsource our customer support to a third-party provider."
    },
    {
      front: "Turnover",
      back: "The total sales or the rate at which employees leave a company",
      example: "The company has a high staff turnover this year."
    },
    {
      front: "Forecast",
      back: "A prediction of future business trends or figures",
      example: "The sales forecast for next quarter looks promising."
    }
  ],

  fillBlank: [
    {
      sentence: "If we _____ the budget, we will need to cut costs.",
      answer: "exceed",
      options: ["exceed", "exceeds", "exceeding", "exceeded"],
      explanation: "After 'if' in first conditional, use present simple: 'exceed'."
    },
    {
      sentence: "The report _____ by the team last night.",
      answer: "was finished",
      options: ["finished", "was finished", "has finished", "is finished"],
      explanation: "Passive voice in past simple: 'was finished'."
    },
    {
      sentence: "I _____ already _____ the client about the delay.",
      answer: "have informed",
      options: ["have informed", "had informed", "will inform", "am informing"],
      explanation: "Present perfect for recent past actions with 'already'."
    },
    {
      sentence: "_____ we schedule a meeting for next Tuesday?",
      answer: "Shall",
      options: ["Shall", "Must", "Ought", "Need"],
      explanation: "‘Shall’ is used for suggestions or offers in formal business contexts."
    },
    {
      sentence: "The budget _____ by the finance department every quarter.",
      answer: "is reviewed",
      options: ["reviews", "is reviewed", "has reviewed", "reviewed"],
      explanation: "Passive voice in present simple: 'is reviewed'."
    }
  ],

  matchPairs: [
    { left: "First of all", right: "used to introduce the first point in a presentation" },
    { left: "In my opinion", right: "used to give a personal view" },
    { left: "Let's move on to", right: "used to transition to the next topic" },
    { left: "To sum up", right: "used to conclude a presentation" },
    { left: "Why don't we", right: "used to make a suggestion" },
    { left: "I'm afraid I disagree", right: "used to politely express disagreement" }
  ],

  reorder: [
    {
      words: ["think", "I", "the", "we", "should", "deadline", "extend"],
      correct: "I think we should extend the deadline."
    },
    {
      words: ["about", "How", "a", "meeting", "scheduling", "next week?"],
      correct: "How about scheduling a meeting next week?"
    },
    {
      words: ["been", "has", "company", "The", "expanding", "rapidly"],
      correct: "The company has been expanding rapidly."
    },
    {
      words: ["will", "if", "profits", "increase", "we", "costs", "reduce"],
      correct: "Profits will increase if we reduce costs."
    },
    {
      words: ["written", "email", "be", "should", "The", "today"],
      correct: "The email should be written today."
    }
  ],

  speaking: [
    {
      text: "In my opinion, the proposal needs more research.",
      phonetic: "/ɪn maɪ əˈpɪnjən ðə prəˈpoʊzəl nidz mɔr rɪˈsɜrtʃ/"
    },
    {
      text: "Let's move on to the next item on the agenda.",
      phonetic: "/lɛts muv ɒn tu ðə nɛkst ˈaɪtəm ɒn ði əˈdʒɛndə/"
    },
    {
      text: "Could you please send me the updated figures?",
      phonetic: "/kʊd ju pliz sɛnd mi ði ʌpˈdeɪtɪd ˈfɪgjərz/"
    },
    {
      text: "I totally agree with what you just said.",
      phonetic: "/aɪ ˈtoʊtəli əˈɡri wɪð wʌt ju dʒʌst sɛd/"
    },
    {
      text: "First, we'll look at the sales report.",
      phonetic: "/fɜrst wil lʊk æt ðə seɪlz rɪˈpɔrt/"
    }
  ],

  dictation: [
    {
      text: "The quarterly report will be ready by Friday."
    },
    {
      text: "We need to discuss the budget for next year."
    },
    {
      text: "Sales have increased by twenty percent this month."
    },
    {
      text: "Could you forward the email to the entire team?"
    },
    {
      text: "If we invest more, we will see better results."
    }
  ],

  listening: [
    {
      text: "Good morning everyone. First, I'd like to discuss our Q3 results. As you can see, revenue increased by 12% compared to last quarter. However, our expenses also went up by 5%. Next, we'll look at the marketing campaign performance.",
      question: "What happened to expenses in Q3?",
      options: [
        "They decreased by 5%",
        "They increased by 12%",
        "They increased by 5%",
        "They remained stable"
      ],
      correct: 2
    },
    {
      text: "If we launch the product next month, we will capture the holiday market. However, we need to finish testing first. Could the development team confirm the timeline by tomorrow?",
      question: "What does the speaker ask the development team to do?",
      options: [
        "Launch the product next month",
        "Confirm the timeline by tomorrow",
        "Capture the holiday market",
        "Finish testing immediately"
      ],
      correct: 1
    },
    {
      text: "I think we should outsource our IT support. In my opinion, it will reduce costs and improve efficiency. What does everyone else think? Let's put it to a vote.",
      question: "What is the speaker's opinion on outsourcing IT support?",
      options: [
        "It will be too expensive",
        "It will reduce costs and improve efficiency",
        "It will increase the workload",
        "It will take too long"
      ],
      correct: 1
    }
  ],

  errorCorrection: [
    {
      incorrect: "I have been to the meeting yesterday.",
      correct: "I went to the meeting yesterday.",
      explanation: "Use past simple (not present perfect) with a specific past time reference like 'yesterday'."
    },
    {
      incorrect: "If we will launch early, we will beat the competition.",
      correct: "If we launch early, we will beat the competition.",
      explanation: "In first conditional, use present simple (not 'will') after 'if'."
    },
    {
      incorrect: "The report was write by Sarah.",
      correct: "The report was written by Sarah.",
      explanation: "Past participle of 'write' is 'written' in passive voice construction."
    },
    {
      incorrect: "I need to discuss about the budget with you.",
      correct: "I need to discuss the budget with you.",
      explanation: "The verb 'discuss' is transitive and does not take the preposition 'about'."
    }
  ],

  sentenceTransformation: [
    {
      prompt: "Send me the contract when you have time.",
      startWith: "Could",
      correct: [
        "Could you send me the contract when you have time?",
        "Could you send me the contract when you have some time?"
      ],
      hint: "Use 'Could you' to make a polite request.",
      explanation: "Transform an imperative into a polite request using 'Could you + base verb'."
    },
    {
      prompt: "The team is reviewing the application now.",
      startWith: "The application",
      correct: [
        "The application is being reviewed by the team now.",
        "The application is being reviewed now by the team."
      ],
      hint: "Use the passive continuous form 'is being + past participle'.",
      explanation: "Change active present continuous to passive: 'is being reviewed'."
    },
    {
      prompt: "I started working here three years ago and still work here.",
      startWith: "I have",
      correct: [
        "I have been working here for three years.",
        "I have worked here for three years."
      ],
      hint: "Use present perfect (continuous) with 'for' to express duration.",
      explanation: "Present perfect shows an action that started in the past and continues."
    },
    {
      prompt: "We might miss the deadline if we are not careful.",
      startWith: "Unless",
      correct: [
        "Unless we are careful, we will miss the deadline.",
        "Unless we are careful we might miss the deadline."
      ],
      hint: "Use 'Unless' to mean 'if not'.",
      explanation: "Rewrite a first conditional using 'unless' + affirmative verb."
    }
  ],

  clozePassage: {
    text: "In our {0} meeting, we discussed the Q2 results. First, the sales team reported that revenue has {1} by 18%. However, if we {2} our marketing spend, we will need to reduce the budget elsewhere. The CEO suggested that the report {3} to all stakeholders by next Friday. In my {4}, this timeline is achievable. Finally, we agreed that the new policy will {5} introduced next month.",
    blanks: [
      {
        correct: "quarterly",
        options: ["weekly", "quarterly", "monthly", "annual"],
        explanation: "Q2 refers to a quarter, so the meeting is quarterly."
      },
      {
        correct: "increased",
        options: ["decreased", "increased", "remained", "dropped"],
        explanation: "An 18% rise means revenue has increased."
      },
      {
        correct: "increase",
        options: ["increased", "will increase", "increase", "increasing"],
        explanation: "First conditional: 'if + present simple'."
      },
      {
        correct: "be sent",
        options: ["send", "be sent", "sending", "sent"],
        explanation: "Passive voice after 'suggested that' — 'be sent'."
      },
      {
        correct: "opinion",
        options: ["opinion", "thought", "idea", "view"],
        explanation: "‘In my opinion’ is a standard phrase for giving a personal perspective."
      },
      {
        correct: "be",
        options: ["be", "being", "been", "is"],
        explanation: "‘Will be introduced’ — future passive voice with 'will + be + past participle'."
      }
    ]
  }
};
